# Generated by Django 5.0.4 on 2024-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
