# Generated by Django 5.0.4 on 2024-06-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneplant', '0002_alter_comments_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
